name: ✨ Feature Request
description: Request a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and README
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - New Model Implementation
        - New Dataset Integration
        - New Evaluation Metric
        - Performance Improvement
        - Documentation Enhancement
        - Visualization/Analysis Tool
        - API Enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Why would this feature be useful? What problem does it solve?
      placeholder: |
        Describe the problem or limitation you're facing...
        How would this feature help you or the community?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of how you envision this feature
      placeholder: |
        How should this feature work?
        What should the API/interface look like?
        Any specific requirements or constraints?

  - type: textarea
    id: model_details
    attributes:
      label: Model Details (if requesting new model)
      description: If requesting a new model implementation, provide details
      placeholder: |
        - Model name and paper reference
        - Model type (e.g., VAE, GAN, Transformer)
        - Key capabilities and advantages
        - Implementation complexity
        - Available code/resources

  - type: textarea
    id: dataset_details
    attributes:
      label: Dataset Details (if requesting new dataset)
      description: If requesting a new dataset integration, provide details
      placeholder: |
        - Dataset name and source
        - Data type and format
        - Size and characteristics
        - Licensing and availability
        - Relevance to perturbation prediction

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered alternative approaches or workarounds?
      placeholder: Describe any alternative solutions you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my work
        - Critical - Blocking my research
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, references, or examples that might help
      placeholder: |
        Links to papers, existing implementations, or examples...
        Screenshots or mockups (if applicable)...